### ISSUE TITLE
Example Please

### ISSUE THREAD

**Issue by ghost** [martinchrzan/FileTransferManager#1]
I not sure what to use in method for Action<IOExtensions.TransferProgress> do you have an example?

This works but does not display any progress
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using FileSystem = IOExtensions.FileTransferManager;

namespace TestApp
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private async void button1_Click(object sender, EventArgs e)
        {
            await FileSystem.CopyWithProgressAsync(@"C:\temp\test", @"D:\temp\test", x => x.Percentage.ToString(), true);
            MessageBox.Show("Done", "Done", MessageBoxButtons.OK, MessageBoxIcon.Information, MessageBoxDefaultButton.Button1, MessageBoxOptions.ServiceNotification);
        }
    }
}

**Comment by martinchrzan** [comment]
This action is called every time the progress is changed, you can use it as
following to show progress somewhere

 await FileSystem.CopyWithProgressAsync(@"C:\temp\test",
@"D:\temp\test", HandleProgressInfo, true);
....

private void HandleProgressInfo(IOExtensions.TransferProgress progress)
{

    Label.Content = progress.Percentage.ToString();

}

But thanks for the question, I will add some documentation on GitHub page.


ut 20. 11. 2018 o 22:26 SFC-Sarge <notifications@github.com> napísal(a):

**Comment by ghost** [comment]
Thanks for the quick response and it works great, You have a great free product here that I will be using to show provisioning process of files and directories under Windows 10 WinPE 1809.  This replaces VisualBasic.dll requirement under C# as I move validate code supports .NET Core 3.0 for a further release.

Thanks for the support you provided me. If you ever need anything from me please ask.
