### ISSUE TITLE
[Question] - Is this Cross Platform? I saw Win32.dll used, so I am unsure

### ISSUE THREAD

**Issue by jeffward01** [martinchrzan/FileTransferManager#12]
Hello!

Will this run on Mac or Linux? I saw [NativeMethods.cs](https://github.com/martinchrzan/FileTransferManager/blob/master/IOExtensions/NativeMethods.cs) which uses `Win32.dll` - so i do not think this is cross-platform... Maybe I am wrong? I hope this is cross platform! <3

Thanks for great library!

**Comment by martinchrzan** [comment]
Unfortunately it is not. It is relying on Win32 API, which exposes internal functionality of Windows itself - this library allows you to access the same functionality that is used by file manager (explorer) in the OS.
