### ISSUE TITLE
[Feature Request] Is it possible to copy the contents of a folder to another folder?

### ISSUE THREAD

**Issue by NickeManarin** [martinchrzan/FileTransferManager#2]
For example, I wish to copy multiple files that I have inside folder `C:\Test `and paste inside folder `C:\Test2`.
(Notice that the folder names are different)

Right now, using this command, it will copy the source folder and paste it inside the destination path:
`await FileTransferManager.CopyWithProgressAsync(source, destination, Progress, false);`
Is there any way to accomplish what I need?  

If it's **not possible** yet, maybe it could be implemented using a simple wildcard:
`await FileTransferManager.CopyWithProgressAsync(source + "\\*", root, Progress, false);`

Or maybe an additional parameter called **Copy the contents of the source folder**.

Thank you for your great project, btw.

**Comment by martinchrzan** [comment]
Hi Nicke,

thanks, good question! 
Currently, you can specify a file and a destination folder so for your case you will do something like:
```
foreach(var file in Directory.GetFiles("C:\Test"))
{
await FileTransferManager.CopyWithProgressAsync(file, "C:\Test2", Progress, false);
}
```
However, I see that this might not be the optimal way to achieve that. I will think about how to solve it in the best way, not to introduce too many overloads and complexity.
I am not very fond of wildcard parameter as it is not self documenting and require some documentation. I might even make it more restrictive a create 2 methods - one with IEnumerable<FileInfo> as source and another as DirectoryInfo to make it more obvious.

**Comment by NickeManarin** [comment]
Thank you Martin Chrzan!

If you don't want to use a wildcard, maybe a second `Boolean` parameter or maybe indeed another method with a different parameter could work.
