### ISSUE TITLE
[Bug] Sanitize source path

### ISSUE THREAD

**Issue by NickeManarin** [martinchrzan/FileTransferManager#3]
When the source path ends with a `\` all the files/folders copied are missing the first letter.

For example:

Test1: **File.txt** and **Image.png**

`await FileTransferManager.CopyWithProgressAsync(@"C:\Test1\", @"C:\Test2", Progress, false);`

Test2: **ile.txt** and **mage.png**

~~(The `\` + **first letter** is acting like a escape sequence)~~
(Actually, there's a substring being used to take the name of the file/folder)

**Comment by NickeManarin** [comment]
As a quick fix, just add this code in the **CopyDirectoryWithProgress** method.

`sourceDirectory = sourceDirectory.TrimEnd('\\');`

**Comment by martinchrzan** [comment]
Thanks! I really need to add tests with virtual file system for this kind of issues! 
For now I fixed it as you suggested - 62774a153b6e6ab72c2e4193119a9849c21ccad4
