### ISSUE TITLE
Why COPY_FILE_RESTARTABLE ?

### ISSUE THREAD

**Issue by nerai** [martinchrzan/FileTransferManager#6]
In https://github.com/martinchrzan/FileTransferManager/blob/68be526ed5fdfff8bb8128d5c76a57c3d3136649/IOExtensions/FileTransferManager.cs#L200
it uses `NativeMethods.CopyFileFlags.COPY_FILE_RESTARTABLE`. Is there a reason to apply this flag?

**Comment by martinchrzan** [comment]
Hi @nerai sorry for the late reply. I set it for increasing reliability of a transfer, but as you said the other flag is improving the speed significantly. I have merged your commit here and I will publish a new nuget with that change. 
Thank you!
